package MS.AOP;
//
//import java.awt.image.BufferedImage;
//
//import AVQ.OEQ.cap.Monitor_XCDX;
//import IMO.EVU.bi_P.CoAuthorForWord;
//import IMS.EUQ.SP.SoundWaveJPanel;
//import ME.APM.VSQ.AppConfig;
//import ME.APM.VSQ.AppHospital;
//import ME.APM.VSQ.AppInit_XCDX;
//import ME.APM.VSQ.AppSearch;
//import ME.APM.VSQ.App_XCDX;
//import ME.APM.VSQ.TagSearch;
//import ME.APM.VSQ.Harrison.CecilPage;
//import ME.APM.VSQ.editPane.EditPane;
//import ME.APM.VSQ.fuchankexue.FckxPage;
//import ME.APM.VSQ.guJiJingDian.FyydPage;
//import ME.APM.VSQ.image.ImageIndex;
//import ME.APM.VSQ.jiZhenKeXue.JzkxPage;
//import ME.APM.VSQ.waiShangKeXue.WskxPage;
//import ME.APM.VSQ.xiYiNeiKe.XynkPage;
//import ME.APM.VSQ.xiYiWaiKe.WkxPage;
//import ME.APM.VSQ.xiYiYaoCai.XyscPage;
//import ME.APM.VSQ.yaoCaiTu.YaoCaiIndex;
//import ME.APM.VSQ.zhongYiFuChan.FqzPage;
//import ME.APM.VSQ.zhongYiNeiKeXue.ZynkxPage;
//import ME.APM.VSQ.zhongYiZhenDuanXue.ZyzdxPage;
//import SVQ.stable.StableTag;
//import MSU.OCI.ME.SMS.translator.C.Translator;
//import MVQ.button.DetaButton;
//import MVQ.tabbedpane.DetabbedPane;
//import MVQ.textfield.CfxTextField;
//import OEI.ME.analysis.E.CogsBinaryForest_AE;
//import OSI.AOP.neo.tts.ReadChinese;
//import OSI.OPE.AOPM.VECS.IDUQ.OVU.PQE.flash.GUISample;
//import OSI.OPE.OEQ.MCQ.OVU.PQE.osgi.OSU_AVQ_ASQ_ASQ_OCQ_OSI_PCI_PCU_MCI_MCU_MSI;
//import java.util.ArrayList;
//import java.util.HashMap;
//import java.util.List;
//import java.util.Map;
//import java.util.concurrent.ConcurrentHashMap;
//import java.util.concurrent.CopyOnWriteArrayList;
//
//import javax.swing.ImageIcon;
//import javax.swing.JButton;
//import javax.swing.JCheckBox;
//import javax.swing.JFrame;
//import javax.swing.JLabel;
//import javax.swing.JPanel;
//import javax.swing.JScrollPane;
//import javax.swing.JSlider;
//import javax.swing.JTextField;
//import javax.swing.JTextPane;
//import javax.swing.table.DefaultTableModel;
//
//import SVQ.stable.StableFile;

public class AppStable {
//	public AppSearch appSearch;
//	public AppHospital appHospital;
//	public AppConfig appConfig;
//	public TagSearch tagSearch;
//	public AppInit_XCDX appInit;
//	public App_XCDX app_XCDX;
//	public String fourInitonSuanTxt= "";
//	public String fourInitonJianTxt= "";
//	public String eightInitonJianTxt= "";
//	public GUISample gUISample;
//	public String databaseRootPath;
//	public List<String> CacheStringPiple= new CopyOnWriteArrayList<>();
//	public Map<String, String> CacheString= new ConcurrentHashMap<>();
//	public JFrame frameConfig;
//	public int rangeHigh= 40;
//	public int row= 0;
//	public SoundWaveJPanel soundWaveJPanel;
//	public int col= 0;
//	public boolean disableCursor= true;
//	public Translator translator;
//	public JTextPane text;
//	public JTextPane jText;
//	protected JTextPane jxText;
//	public String key;
//	public JFrame frame;
//	public JFrame frameHospital;
//	public String hint;
////	public AppSearch appSearch;
////	public AppHospital appHospital;
////	public AppConfig appConfig;
//	public CogsBinaryForest_AE _A;
//	public CoAuthorForWord coAuthorForWord;
//	public Monitor_XCDX monitor;
//	public JSlider look;
//	public Map<String, String> pos;
//	public Map<String, String> posec;
//	public Map<String, String> pose;
//	public Map<String, String> posFullec;
//	public Map<String, String> posFullce;
//	public Map<String, String> etc;
//	public Map<String, String> cte;
//	public Map<String, String> pinyin;
//	public Map<String, String> ctk;
//	public Map<String, String> ctj;
//	public Map<String, String> ctt;
//	public List<OSU_AVQ_ASQ_ASQ_OCQ_OSI_PCI_PCU_MCI_MCU_MSI> searchList= new ArrayList<>();; 
//	public JCheckBox risk_filter_box;
//	public JCheckBox feel_filter_box;
//	public JCheckBox jingmai_filter_box;
//	public JCheckBox gongxiao_filter_box;
//	public JCheckBox zonghe_filter_box;
//	public JCheckBox shuming_filter_box;
//	public DetabbedPane jTabbedpane;
//	public List<String> sets;
//	public XynkPage xynkPage;
//	public ZynkxPage zynkxPage;
//	public ZyzdxPage zyzdxPage;
//	public FyydPage fyydPage;
//	public FqzPage fqzPage;
//	public FckxPage fckxPage;
//	public JzkxPage jzkxPage;
//	public WkxPage wkxPage;
//	public WskxPage wskxPage;
//	public XyscPage xyscPage;
//	public CecilPage cecil;
//	public EditPane editPane;
//	public JLabel yaoCaiLabel;
//	public JTextPane data;
//	public JPanel panel_yt;
//	public JTextField name;
//	public JTextField nameHospital;
//	public JTextField name_filter;
//	public javax.swing.JTable table;  
//	public Object[][] tableData_old;
//	public DefaultTableModel newTableModel= null;
//	public List<String> dic_list;
//	public List<String> copy;
//	public Map<String, Object> dic_map= new HashMap<>();
//	public Map<String, Object> dic_li= new HashMap<>();
//	public Map<String, Object> dic_hai= new HashMap<>();
//	public Map<String, Object> dic_xz= new HashMap<>();
//	public Map<String, Object> dic_ya= new HashMap<>();
//	public Map<String, Object> dic_jm= new HashMap<>();
//	public Map<String, Object> dic_xw= new HashMap<>();
//	public Map<String, Object> dic_cy= new HashMap<>();
//	public Map<String, Object> dic_cj= new HashMap<>();
//	public Map<String, Object> dic_jj= new HashMap<>();
//	public Map<String, Object> dic_zf= new HashMap<>();
//	public Map<String, Object> dic_yl= new HashMap<>();
//	public Map<String, Object> dic_yw= new HashMap<>();
//	public Map<String, Object> dic_index= new HashMap<>();
//	public JPanel panel= new JPanel(); 
//	public JButton buttonCTE;
//	public JButton buttonFRS;
//	public JButton buttonETC;
//	public JButton buttonADD;
//	public JButton buttonGXB;
//	public JButton buttonBCJ;
//	public JFrame frameTag;
//	//public TagSearch tagSearch;
//	public ImageIcon logo= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.logo_png));  
//	public ImageIcon pnga= new ImageIcon(this.getClass().getResource(StableFile.sc_a_png)); 
//	public ImageIcon pngo= new ImageIcon(this.getClass().getResource(StableFile.sc_o_png)); 
//	public ImageIcon pnge= new ImageIcon(this.getClass().getResource(StableFile.sc_e_png)); 
//	public ImageIcon pngi= new ImageIcon(this.getClass().getResource(StableFile.sc_i_png)); 
//	public ImageIcon pngu= new ImageIcon(this.getClass().getResource(StableFile.sc_u_png)); 
//	public ImageIcon shoujueyin= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.手厥阴心包经_png)); 
//	public ImageIcon shoushaoyang= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.手少阳三焦经_png));  
//	public ImageIcon shoushaoyin= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.手少阴心经_png));  
//	public ImageIcon shoutaiyang= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.手太阳小肠经_png));  
//	public ImageIcon shoutaiyin= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.手太阴肺经_png));  
//	public ImageIcon shouyangmin= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.手阳明大肠经_png));  
//	public ImageIcon zujueyin= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.足厥阴肝经_png));  
//	public ImageIcon zushaoyang= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.足少阳胆经_png));
//	public ImageIcon zushaoyin= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.足少阴肾经_png));  
//	public ImageIcon zutaiyang= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.足太阳膀胱经_png));  
//	public ImageIcon zutaiyin= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.足太阴脾经_png));  
//	public ImageIcon zuyangmin= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.足阳明胃经_png));  
//	public ImageIcon png88 = new ImageIcon(new ImageIndex().getClass().getResource(StableFile.bagua_png));  
//	public ImageIcon wsp = new ImageIcon(new ImageIndex().getClass().getResource(StableFile.wsp_png));  
//	public ImageIcon wwp = new ImageIcon(new ImageIndex().getClass().getResource(StableFile.wwp_png));  
//	public ImageIcon wxp = new ImageIcon(new ImageIndex().getClass().getResource(StableFile.wxp_png));
//	public ImageIcon shun = new ImageIcon(new ImageIndex().getClass().getResource(StableFile.shun_png));  
//	public ImageIcon bagua_bgbz= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.bagua_bgbz_png));  
//	public ImageIcon bagua_ljbz= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.bagua_ljbz_png));  
//	public ImageIcon bagua_sjbz= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.bagua_sjbz_png));
//	public ImageIcon bagua_qxbz= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.bagua_qxbz_png));  
//	public ImageIcon bagua_gzxs= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.bagua_gzxs_png));  
//	public ImageIcon bagua_skch= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.bagua_skch_png));  
//	public ImageIcon bagua_MHYS= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.bagua_MHYS_png));  
//	public ImageIcon bagua_YHZP= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.bagua_YHZP_png));  
//	public ImageIcon bagua_QNZS= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.bagua_QNZS_png)); 
//	public ImageIcon bagua_YDLR= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.bagua_YDLR_png)); 
//	public ImageIcon bagua_HLLS= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.bagua_HLLS_png)); 
//	public ImageIcon bagua_ZSBZ= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.bagua_ZSBZ_png));
//	public ImageIcon bagua_KYCQ= new ImageIcon(new ImageIndex().getClass().getResource(StableFile.bagua_KYCQ_png));
//	public ImageIcon qp4= new ImageIcon(new ImageIndex().getClass().getResource(StableFile._4qp_png));  
//	public ImageIcon pngy_2_1= new ImageIcon(new YaoCaiIndex().getClass().getResource(StableFile.yc_2_1_png));  
//	public Object[] columnTitle= {StableTag.columnTitle_0, StableTag.columnTitle_1, StableTag.columnTitle_2
//			, StableTag.columnTitle_3, StableTag.columnTitle_4, StableTag.columnTitle_5, StableTag.columnTitle_6
//			, StableTag.columnTitle_7, StableTag.columnTitle_8, StableTag.columnTitle_9, StableTag.columnTitle_10
//			, StableTag.columnTitle_11, StableTag.columnTitle_12, StableTag.columnTitle_13, StableTag.columnTitle_14};
//	public CfxTextField name_filter_not_have;
//	public Map<String, String> ctr;
//	public CfxTextField nameFeelFilter;
//	public JScrollPane jsp_name= null;
//	public boolean ready= false;
//	public AppStable appInstance;
//	public ReadChinese readChinese;
//	public DetaButton buttonCTV;
//	public int lookrot;
//	public List<String> tabNames;
//	public BufferedImage tempBufferedImage;
//	public int 催化比值rot;
//	public boolean DNASearchIsClick;
//	//public AppInit_XCDX appInit;
//	public String dbConfigPath;
//	public boolean bootDBInTXTWay= false;
//	public boolean bootDBInBaseWay= false;
//	public boolean bootDBInWebWay= false;
//	//public App_XCDX app_XCDX;
//	public JPanel jPanel;
//	public JScrollPane jsp_name_filter;
//	public JLabel jlabel_filter;
//	public JScrollPane jsp_name_filter_not_have;
//	public JLabel jlabel_filter_not_have;
//	public JLabel risk_filter;
//	public JLabel feel_filter;
//	public JLabel xingwei_filter;
//	public JScrollPane jsp_nameFeelFilter;
//	public JLabel jingmai_filter;
//	public JLabel zonghe_filter;
//	public JLabel shuming_filter;
//	public JScrollPane jScrollPane;
//	
//	public String fourInitonSuanFaTxt;
//	public String fourInitonSuanBiTxt;
//	public String fourInitonSuanJingTxt;
//	public String fourInitonSuanPCATxt;
//	public String fourInitonSuanECATxt;
//	public String fourInitonSuanUPCATxt;
//	public String fourInitonSuanICATxt;
//
//	public String fourInitonJianFaTxt;
//	public String fourInitonJianBiTxt;
//	public String fourInitonJianJingTxt;
//	public String fourInitonJianPCATxt;
//	public String fourInitonJianECATxt;
//	public String fourInitonJianUPCATxt;
//	public String fourInitonJianICATxt;
//		
//	public String eightInitonJianFaTxt;
//	public String eightInitonJianBiTxt;
//	public String eightInitonJianJingTxt;
//	public String eightInitonJianPCATxt;
//	public String eightInitonJianECATxt;
//	public String eightInitonJianUPCATxt;
//	public String eightInitonJianICATxt;
//	
//	public String fourInitonSuanFuTxt;
//	public String fourInitonJianFuTxt;
//	public String eightInitonJianFuTxt;
//	
//	public String 前端接口Txt;
//	public String 后端接口Txt;
//	public String 数据库接口Txt;
//	public String 缓存接口Txt;
//	public String 蓝牙接口Txt;
//	public String Tel终端Txt;
}